name: expenses_tracker_lite

description: "Expenses Tracker Lite"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.2.0
  flutter_hooks: ^0.21.3
  dio: ^5.9.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  intl: ^0.20.2
  flutter_dotenv: ^5.1.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  intl_utils: ^2.8.7
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter_intl:
  # The CLI to generate the translations
  # dart run intl_utils:generate
  enabled: true
  class_name: AppLocalizations
  main_locale: ar
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false

flutter:

  uses-material-design: true

  assets:
    - .env
